### ISSUE TITLE
Page does not reload after submiting tags

### ISSUE THREAD

**Issue by Majkel1999** [Majkel1999/Hilbert#47]
After clicking "Submit tags" button on annotator view, the page does not reload. Every next click results in **409** status code, because the text has already been tagged.

The dispatch event should return the status code, and a proper message should be displayed instead.

**Comment by Kacper12445** [comment]
Displaying proper message will be available as soon as we finish snack bar. As far as I know it's almost finished, so we will try to implement it in next 2 days

**Comment by Majkel1999** [comment]
Fixed
